
# ~BrieFlow analysis configuration file~

# All paths are resolved relative to the directory the workflow is run from.

# Parameters:
all:
  root_fp: brieflow_output/
preprocess:
  sbs_samples_fp: config/sbs_samples.tsv
  sbs_combo_fp: config/sbs_combo.tsv
  phenotype_samples_fp: config/phenotype_samples.tsv
  phenotype_combo_fp: config/phenotype_combo.tsv
  segment_samples_fp: config/segment_samples.tsv
  segment_combo_fp: config/segment_combo.tsv
  sbs_channel_order: null
  phenotype_channel_order: null
  segment_order: null
  phenotype_round_order:
  - 1
  - 2
  sbs_channel_order_flip: false
  phenotype_channel_order_flip: false
  segment_channel_order_flip: false
  sample_fraction: 0.1
sbs:
  alignment_method: DAPI
  channel_names:
  - DAPI
  - G
  - T
  - A
  - C
  upsample_factor: 2
  skip_cycles_indices: null
  manual_background_cycle_index: null
  extra_channel_indices:
  - 0
  max_filter_width: 3
  spot_detection_method: standard
  dapi_cycle: 1
  cyto_cycle: 1
  cyto_cycle_index: 0
  dapi_index: 0
  cyto_index: 1
  segmentation_method: cellpose
  gpu: true
  reconcile: contained_in_cells
  segment_cells: true
  use_segmentation_images: true
  segmentation_upsample_factor: 2
  segmentation_window: 2
  df_barcode_library_fp: config/barcode_library.tsv
  threshold_peaks: 500
  call_reads_method: percentile
  bases:
  - G
  - T
  - A
  - C
  q_min: 0.42
  barcode_col: sgRNA
  prefix_col: prefix
  error_correct: true
  sort_calls: count
  mode: null
  peak_width: 5
  nuclei_diameter: 13.727325035155395
  cell_diameter: 43.21854245721949
  nuclei_flow_threshold: 0.4
  nuclei_cellprob_threshold: 0.0
  cell_flow_threshold: 0.8
  cell_cellprob_threshold: 0
  cyto_model: cyto3
phenotype:
  foci_channel: null
  channel_names:
  - EpCAM
  - CRISPRi
  - Ki67
  - ZEB1
  - VIM
  - DAPI
  - CRISPRi_2
  - PHA
  - WGA
  align: true
  dapi_index: 5
  cyto_index: 7
  segmentation_method: cellpose
  reconcile: contained_in_cells
  gpu: true
  cp_method: cp_multichannel
  mode: null
  nuclei_diameter: 62.68346859462001
  cell_diameter: 132.7320737849024
  nuclei_flow_threshold: 0.4
  nuclei_cellprob_threshold: 0.0
  cell_flow_threshold: 0.9
  cell_cellprob_threshold: 0
  cyto_model: cyto3
  target: 1
  source: 6
  riders:
  - 2
  - 3
  - 4
  - 5
  - 7
  - 8
  remove_channel: null
